printf "Openshift Host:\n"
printf "${OPENSHIFT_MASTER_HOST}\n"
printf "Hawkular Host:\n"
printf "${OPENSHIFT_HAWKULAR_ROUTE}\n"
printf "Prometheus Alerts Host:\n"
printf "${OPENSHIFT_PROMETHEUS_ALERTS_ROUTE}\n"
printf "Prometheus Metrics Host:\n"
printf "${OPENSHIFT_PROMETHEUS_METRICS_ROUTE}\n"
printf "Openshift Console:\n"
printf "https://${OPENSHIFT_MASTER_HOST}:8443/console/\n"

printf "Token:\n"
printf "${OPENSHIFT_MANAGEMENT_ADMIN_TOKEN}\n"
